# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmWindowTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmWindowTwo(object):
    def setupUi(self, frmWindowTwo):
        frmWindowTwo.setObjectName("frmWindowTwo")
        frmWindowTwo.resize(111, 55)
        self.lblHello = QtWidgets.QLabel(frmWindowTwo)
        self.lblHello.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.lblHello.setObjectName("lblHello")

        self.retranslateUi(frmWindowTwo)
        QtCore.QMetaObject.connectSlotsByName(frmWindowTwo)

    def retranslateUi(self, frmWindowTwo):
        _translate = QtCore.QCoreApplication.translate
        frmWindowTwo.setWindowTitle(_translate("frmWindowTwo", "Form"))
        self.lblHello.setText(_translate("frmWindowTwo", "Hello Again"))



