# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 138)
        self.btnRun = QtWidgets.QPushButton(Form)
        self.btnRun.setGeometry(QtCore.QRect(20, 20, 89, 25))
        self.btnRun.setObjectName("btnRun")
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setGeometry(QtCore.QRect(20, 60, 89, 25))
        self.btnStop.setObjectName("btnStop")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 100, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(200, 20, 50, 64))
        self.dial.setObjectName("dial")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(260, 20, 64, 71))
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Test Thread"))
        self.btnRun.setText(_translate("Form", "Run"))
        self.btnStop.setText(_translate("Form", "Stop"))


